### ISSUE TITLE
Doesnt work with revscript, sad.

### ISSUE THREAD

**Issue by michu940107** [Oen44/TFS-Upgrade-System#2]

**Comment by LeoTKBR** [comment]
estou usando em revscript deu para converter facilmente

**Comment by michu940107** [comment]
> estou usando em revscript deu para converter facilmente

POST THEM PLEASE

**Comment by LeoTKBR** [comment]
Me chama no discord LeoTK#3957

**Comment by Oen44** [comment]
No.
