### ISSUE TITLE
Reset upgrade itens

### ISSUE THREAD

**Issue by LeoTKBR** [Oen44/TFS-Upgrade-System#3]
Original Weapon
![2](https://user-images.githubusercontent.com/41605307/118349177-82ee3a00-b525-11eb-979b-8cb10edd41dd.png)

After Upgrade
![4](https://user-images.githubusercontent.com/41605307/118349183-8a154800-b525-11eb-822d-8308e12326b0.png)

**Comment by Oen44** [comment]
https://github.com/Oen44/TFS-Upgrade-System/wiki/developer-notes

**Comment by LeoTKBR** [comment]
when even dropping monsters comes level 0?
