### ISSUE TITLE
Erro loading script on server.

### ISSUE THREAD

**Issue by Tenshimaru** [Oen44/TFS-Upgrade-System#4]
![image](https://user-images.githubusercontent.com/61519926/149581554-f64ff188-63bf-4321-802d-809116a12288.png)

All events mentioned are enabled, and folder in on the correct places.

The line on **core.lua**

![image](https://user-images.githubusercontent.com/61519926/149581727-2c66caec-4c73-4cd1-94bc-b282b3056134.png)

**Comment by Oen44** [comment]
You are no using TFS 1.4+ or don't have EventCallback.
Use https://github.com/Oen44/TFS-Upgrade-System/tree/pre-1.4 instead

**Comment by Tenshimaru** [comment]
My version uses RevScript, show a lot of erros when i try to use the pre 1.4
Theres some adapatation that i can do to make it work?

Distro: OpenTibiabr

**Comment by Oen44** [comment]
I'm not supporting that distro.
